'''Ex.008'''
m = float(input('Digite um valor em metros:'))
km = float(m / 1000)
hm = float(m / 100)
dam = float(m / 10)
dm = float(m * 10)
cm = float(m * 100)
mm = float(m * 1000)
print('{} metros é equivalente a \n{} Quilometros \n{} Hectômetros \n{} Decâmetros'.format(m, km, hm, dam))
print('{} Decímetros \n{} Centímetros e \n{} Milímetros'.format(dm, cm, mm))
