nome = input("digite algo")
print("O tipo primitivo desse valor é", type(nome))
print("Só tem espaços?", nome.isspace())
print("É um número?", nome.isnumeric())
print("É alfabético?", nome.isalpha())
print("É alfanumérico?", nome.isalnum())
print("Está em maiusculas?", nome.isupper())
print("Está em minúsculas?", nome.islower())
print("Está capitalizada?", nome.istitle())
